// Command gentables dumps Go unicode.Categories/Scripts (and Fold*) into Rust.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"unicode"
)

type named struct {
	name string
	tab  *unicode.RangeTable
	fold *unicode.RangeTable
}

func sortedNames(m map[string]*unicode.RangeTable) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

func main() {
	_, this, _, ok := runtime.Caller(0)
	if !ok {
		fmt.Fprintln(os.Stderr, "no caller")
		os.Exit(1)
	}
	outPath := filepath.Join(filepath.Dir(this), "..", "..", "src", "unicode_tables.rs")

	var cats, scripts []named
	for _, k := range sortedNames(unicode.Categories) {
		cats = append(cats, named{k, unicode.Categories[k], unicode.FoldCategory[k]})
	}
	for _, k := range sortedNames(unicode.Scripts) {
		scripts = append(scripts, named{k, unicode.Scripts[k], unicode.FoldScript[k]})
	}

	var tables []*unicode.RangeTable
	idx := map[string]int{}
	add := func(t *unicode.RangeTable) int {
		if t == nil {
			return -1
		}
		key := fmt.Sprintf("%p", t)
		if i, ok := idx[key]; ok {
			return i
		}
		i := len(tables)
		tables = append(tables, t)
		idx[key] = i
		return i
	}
	for _, n := range cats {
		add(n.tab)
		add(n.fold)
	}
	for _, n := range scripts {
		add(n.tab)
		add(n.fold)
	}

	var b strings.Builder
	b.WriteString("// Code generated by tools/gentables from Go unicode.Categories/Scripts. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// unicode.Version = %q (Go %s)\n\n", unicode.Version, runtime.Version())
	b.WriteString("#[derive(Clone, Copy)]\n")
	b.WriteString("pub struct Range16 { pub lo: u16, pub hi: u16, pub stride: u16 }\n")
	b.WriteString("#[derive(Clone, Copy)]\n")
	b.WriteString("pub struct Range32 { pub lo: u32, pub hi: u32, pub stride: u32 }\n")
	b.WriteString("pub struct RangeTable { pub r16: &'static [Range16], pub r32: &'static [Range32] }\n\n")

	b.WriteString("static ANY_R16: &[Range16] = &[Range16 { lo: 0, hi: 65535, stride: 1 }];\n")
	b.WriteString("static ANY_R32: &[Range32] = &[Range32 { lo: 65536, hi: 0x10ffff, stride: 1 }];\n")
	b.WriteString("pub static ANY_TABLE: RangeTable = RangeTable { r16: ANY_R16, r32: ANY_R32 };\n\n")

	for i, t := range tables {
		fmt.Fprintf(&b, "static R16_%d: &[Range16] = &[\n", i)
		for _, r := range t.R16 {
			fmt.Fprintf(&b, "    Range16 { lo: %d, hi: %d, stride: %d },\n", r.Lo, r.Hi, r.Stride)
		}
		b.WriteString("];\n")
		fmt.Fprintf(&b, "static R32_%d: &[Range32] = &[\n", i)
		for _, r := range t.R32 {
			fmt.Fprintf(&b, "    Range32 { lo: %d, hi: %d, stride: %d },\n", r.Lo, r.Hi, r.Stride)
		}
		b.WriteString("];\n")
	}
	b.WriteString("\nstatic TABLES: &[RangeTable] = &[\n")
	for i := range tables {
		fmt.Fprintf(&b, "    RangeTable { r16: R16_%d, r32: R32_%d },\n", i, i)
	}
	b.WriteString("];\n\n")

	writeIndex := func(label string, items []named) {
		fmt.Fprintf(&b, "static %s: &[(&str, u16, i16)] = &[\n", label)
		for _, n := range items {
			fmt.Fprintf(&b, "    (%q, %d, %d),\n", n.name, add(n.tab), add(n.fold))
		}
		b.WriteString("];\n\n")
	}
	writeIndex("CATEGORIES", cats)
	writeIndex("SCRIPTS", scripts)

	b.WriteString(`fn lookup(index: &[(&str, u16, i16)], name: &str) -> Option<(&'static RangeTable, Option<&'static RangeTable>)> {
    let i = index.binary_search_by_key(&name, |&(n, _, _)| n).ok()?;
    let (_, ti, fi) = index[i];
    let tab = &TABLES[ti as usize];
    let fold = if fi < 0 { None } else { Some(&TABLES[fi as usize]) };
    Some((tab, fold))
}

pub fn unicode_table(name: &str) -> Option<(&'static RangeTable, Option<&'static RangeTable>)> {
    if name == "Any" {
        return Some((&ANY_TABLE, Some(&ANY_TABLE)));
    }
    lookup(CATEGORIES, name).or_else(|| lookup(SCRIPTS, name))
}
`)

	if err := os.WriteFile(outPath, []byte(b.String()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Printf("wrote %s (%d tables, %d categories, %d scripts, unicode %s, %s)\n",
		outPath, len(tables), len(cats), len(scripts), unicode.Version, runtime.Version())
}
