import api from './index.js';
export const {
  MailError,
  MailHeader,
  MailAddress,
  MailMessage,
  AddressParser,
  readMessage,
  parseAddress,
  parseAddressList,
  parseDate,
  SmtpError,
  FeatureNotBuiltError,
  SmtpClient,
  SmtpDataWriter,
  plainAuth,
  loginAuth,
  cramMd5Auth,
  sendMail,
} = api;
