import api from './index.js';
export const {
  versionCompare,
  versionIsValid,
  versionLang,
  GoConstValue,
  constMakeInt64,
  constToInt,
  constCompare,
  constSign,
  constBitLen,
  TOKEN,
  SCAN_MODE,
  PARSE_MODE,
  tokenLookup,
  tokenIsKeyword,
  tokenIsExported,
  tokenString,
  FileSet,
  GoFile,
  Scanner,
  GoScanError,
  GoParseError,
  UnsupportedFeatureError,
  parseFile,
  parseExpr,
  astFprint,
  astInspect,
  astIsExported,
  astNewIdent,
} = api;
