// Port of Go regexp/syntax perl_groups.go (generated by make_perl_groups.pl).

pub struct CharGroup {
    pub sign: i32,
    pub class: &'static [i32],
}

static CODE_D: &[i32] = &[0x30, 0x39];
static CODE_S: &[i32] = &[0x9, 0xa, 0xc, 0xd, 0x20, 0x20];
static CODE_W: &[i32] = &[0x30, 0x39, 0x41, 0x5a, 0x5f, 0x5f, 0x61, 0x7a];
static CODE_ALNUM: &[i32] = &[0x30, 0x39, 0x41, 0x5a, 0x61, 0x7a];
static CODE_ALPHA: &[i32] = &[0x41, 0x5a, 0x61, 0x7a];
static CODE_ASCII: &[i32] = &[0x0, 0x7f];
static CODE_BLANK: &[i32] = &[0x9, 0x9, 0x20, 0x20];
static CODE_CNTRL: &[i32] = &[0x0, 0x1f, 0x7f, 0x7f];
static CODE_DIGIT: &[i32] = &[0x30, 0x39];
static CODE_GRAPH: &[i32] = &[0x21, 0x7e];
static CODE_LOWER: &[i32] = &[0x61, 0x7a];
static CODE_PRINT: &[i32] = &[0x20, 0x7e];
static CODE_PUNCT: &[i32] = &[0x21, 0x2f, 0x3a, 0x40, 0x5b, 0x60, 0x7b, 0x7e];
static CODE_SPACE: &[i32] = &[0x9, 0xd, 0x20, 0x20];
static CODE_UPPER: &[i32] = &[0x41, 0x5a];
static CODE_WORD: &[i32] = &[0x30, 0x39, 0x41, 0x5a, 0x5f, 0x5f, 0x61, 0x7a];
static CODE_XDIGIT: &[i32] = &[0x30, 0x39, 0x41, 0x46, 0x61, 0x66];

pub fn perl_group(name: &str) -> Option<CharGroup> {
    Some(match name {
        r"\d" => CharGroup { sign: 1, class: CODE_D },
        r"\D" => CharGroup { sign: -1, class: CODE_D },
        r"\s" => CharGroup { sign: 1, class: CODE_S },
        r"\S" => CharGroup { sign: -1, class: CODE_S },
        r"\w" => CharGroup { sign: 1, class: CODE_W },
        r"\W" => CharGroup { sign: -1, class: CODE_W },
        _ => return None,
    })
}

pub fn posix_group(name: &str) -> Option<CharGroup> {
    Some(match name {
        "[:alnum:]" => CharGroup { sign: 1, class: CODE_ALNUM },
        "[:^alnum:]" => CharGroup { sign: -1, class: CODE_ALNUM },
        "[:alpha:]" => CharGroup { sign: 1, class: CODE_ALPHA },
        "[:^alpha:]" => CharGroup { sign: -1, class: CODE_ALPHA },
        "[:ascii:]" => CharGroup { sign: 1, class: CODE_ASCII },
        "[:^ascii:]" => CharGroup { sign: -1, class: CODE_ASCII },
        "[:blank:]" => CharGroup { sign: 1, class: CODE_BLANK },
        "[:^blank:]" => CharGroup { sign: -1, class: CODE_BLANK },
        "[:cntrl:]" => CharGroup { sign: 1, class: CODE_CNTRL },
        "[:^cntrl:]" => CharGroup { sign: -1, class: CODE_CNTRL },
        "[:digit:]" => CharGroup { sign: 1, class: CODE_DIGIT },
        "[:^digit:]" => CharGroup { sign: -1, class: CODE_DIGIT },
        "[:graph:]" => CharGroup { sign: 1, class: CODE_GRAPH },
        "[:^graph:]" => CharGroup { sign: -1, class: CODE_GRAPH },
        "[:lower:]" => CharGroup { sign: 1, class: CODE_LOWER },
        "[:^lower:]" => CharGroup { sign: -1, class: CODE_LOWER },
        "[:print:]" => CharGroup { sign: 1, class: CODE_PRINT },
        "[:^print:]" => CharGroup { sign: -1, class: CODE_PRINT },
        "[:punct:]" => CharGroup { sign: 1, class: CODE_PUNCT },
        "[:^punct:]" => CharGroup { sign: -1, class: CODE_PUNCT },
        "[:space:]" => CharGroup { sign: 1, class: CODE_SPACE },
        "[:^space:]" => CharGroup { sign: -1, class: CODE_SPACE },
        "[:upper:]" => CharGroup { sign: 1, class: CODE_UPPER },
        "[:^upper:]" => CharGroup { sign: -1, class: CODE_UPPER },
        "[:word:]" => CharGroup { sign: 1, class: CODE_WORD },
        "[:^word:]" => CharGroup { sign: -1, class: CODE_WORD },
        "[:xdigit:]" => CharGroup { sign: 1, class: CODE_XDIGIT },
        "[:^xdigit:]" => CharGroup { sign: -1, class: CODE_XDIGIT },
        _ => return None,
    })
}
