// Command gentables dumps Go 1.24 unicode tables into Rust source and JSON fixtures.
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"unicode"
	"unicode/utf16"
	"unicode/utf8"
)

type namedTable struct {
	Name  string
	Table *unicode.RangeTable
}

func allNamedTables() []namedTable {
	m := map[string]*unicode.RangeTable{}
	add := func(name string, t *unicode.RangeTable) {
		if t == nil {
			panic("nil table " + name)
		}
		m[name] = t
	}
	for k, t := range unicode.Categories {
		add(k, t)
	}
	for k, t := range unicode.Scripts {
		add(k, t)
	}
	for k, t := range unicode.Properties {
		add(k, t)
	}
	add("Digit", unicode.Digit)
	add("Letter", unicode.Letter)
	add("Lower", unicode.Lower)
	add("Mark", unicode.Mark)
	add("Number", unicode.Number)
	add("Other", unicode.Other)
	add("Punct", unicode.Punct)
	add("Space", unicode.Space)
	add("Symbol", unicode.Symbol)
	add("Title", unicode.Title)
	add("Upper", unicode.Upper)
	add("STerm", unicode.STerm)
	names := make([]string, 0, len(m))
	for n := range m {
		names = append(names, n)
	}
	sort.Strings(names)
	out := make([]namedTable, 0, len(names))
	for _, n := range names {
		out = append(out, namedTable{n, m[n]})
	}
	return out
}

func uniqueTables(named []namedTable) (tables []*unicode.RangeTable, index map[string]int) {
	index = map[string]int{}
	ptr := map[string]int{}
	for _, n := range named {
		key := fmt.Sprintf("%p", n.Table)
		if i, ok := ptr[key]; ok {
			index[n.Name] = i
			continue
		}
		i := len(tables)
		tables = append(tables, n.Table)
		ptr[key] = i
		index[n.Name] = i
	}
	return tables, index
}

func writeGeneratedRust(dir string, named []namedTable) {
	tables, index := uniqueTables(named)
	var b strings.Builder
	b.WriteString("// Code generated by tools/gentables. DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("// unicode.Version = %q (Go %s)\n\n", unicode.Version, runtime.Version()))
	b.WriteString("pub const UNICODE_VERSION: &str = \"" + unicode.Version + "\";\n")
	b.WriteString("#[allow(dead_code)]\n")
	b.WriteString("pub const TABLE_COUNT: usize = " + fmt.Sprint(len(named)) + ";\n\n")
	b.WriteString("#[derive(Clone, Copy)]\n")
	b.WriteString("pub struct Range16 { pub lo: u16, pub hi: u16, pub stride: u16 }\n")
	b.WriteString("#[derive(Clone, Copy)]\n")
	b.WriteString("pub struct Range32 { pub lo: u32, pub hi: u32, pub stride: u32 }\n")
	b.WriteString("pub struct RangeTable { pub r16: &'static [Range16], pub r32: &'static [Range32], pub latin_offset: u32 }\n")
	b.WriteString("pub struct CaseRange { pub lo: u32, pub hi: u32, pub delta: [i32; 3] }\n")
	b.WriteString("pub const UPPER_LOWER: i32 = 0x110000;\n\n")

	for i, t := range tables {
		fmt.Fprintf(&b, "static R16_%d: &[Range16] = &[\n", i)
		for _, r := range t.R16 {
			fmt.Fprintf(&b, "    Range16 { lo: %d, hi: %d, stride: %d },\n", r.Lo, r.Hi, r.Stride)
		}
		b.WriteString("];\n")
		fmt.Fprintf(&b, "static R32_%d: &[Range32] = &[\n", i)
		for _, r := range t.R32 {
			fmt.Fprintf(&b, "    Range32 { lo: %d, hi: %d, stride: %d },\n", r.Lo, r.Hi, r.Stride)
		}
		b.WriteString("];\n")
	}
	b.WriteString("\npub static TABLES: &[RangeTable] = &[\n")
	for i, t := range tables {
		fmt.Fprintf(&b, "    RangeTable { r16: R16_%d, r32: R32_%d, latin_offset: %d },\n", i, i, t.LatinOffset)
	}
	b.WriteString("];\n\n")
	b.WriteString("pub static TABLE_INDEX: &[(&str, u16)] = &[\n")
	for _, n := range named {
		fmt.Fprintf(&b, "    (%q, %d),\n", n.Name, index[n.Name])
	}
	b.WriteString("];\n\n")

	b.WriteString("pub static CASE_RANGES: &[CaseRange] = &[\n")
	for _, cr := range unicode.CaseRanges {
		d0, d1, d2 := int32(cr.Delta[unicode.UpperCase]), int32(cr.Delta[unicode.LowerCase]), int32(cr.Delta[unicode.TitleCase])
		fmt.Fprintf(&b, "    CaseRange { lo: %d, hi: %d, delta: [%d, %d, %d] },\n", cr.Lo, cr.Hi, d0, d1, d2)
	}
	b.WriteString("];\n\n")

	b.WriteString("pub static TURKISH_CASE: &[CaseRange] = &[\n")
	for _, cr := range unicode.TurkishCase {
		d0, d1, d2 := int32(cr.Delta[unicode.UpperCase]), int32(cr.Delta[unicode.LowerCase]), int32(cr.Delta[unicode.TitleCase])
		fmt.Fprintf(&b, "    CaseRange { lo: %d, hi: %d, delta: [%d, %d, %d] },\n", cr.Lo, cr.Hi, d0, d1, d2)
	}
	b.WriteString("];\n\n")

	type pair struct{ from, to uint32 }
	var folds []pair
	for r := rune(0); r <= unicode.MaxRune; r++ {
		n := unicode.SimpleFold(r)
		if n != r {
			folds = append(folds, pair{uint32(r), uint32(n)})
		}
	}
	b.WriteString("pub static SIMPLE_FOLD: &[(u32, u32)] = &[\n")
	for _, p := range folds {
		fmt.Fprintf(&b, "    (%d, %d),\n", p.from, p.to)
	}
	b.WriteString("];\n\n")

	b.WriteString("pub static LATIN1_PRED: &[u16; 256] = &[\n")
	for r := 0; r < 256; r++ {
		var bits uint16
		rr := rune(r)
		if unicode.IsControl(rr) {
			bits |= 1 << 0
		}
		if unicode.IsDigit(rr) {
			bits |= 1 << 1
		}
		if unicode.IsGraphic(rr) {
			bits |= 1 << 2
		}
		if unicode.IsLetter(rr) {
			bits |= 1 << 3
		}
		if unicode.IsLower(rr) {
			bits |= 1 << 4
		}
		if unicode.IsMark(rr) {
			bits |= 1 << 5
		}
		if unicode.IsNumber(rr) {
			bits |= 1 << 6
		}
		if unicode.IsPrint(rr) {
			bits |= 1 << 7
		}
		if unicode.IsPunct(rr) {
			bits |= 1 << 8
		}
		if unicode.IsSpace(rr) {
			bits |= 1 << 9
		}
		if unicode.IsSymbol(rr) {
			bits |= 1 << 10
		}
		if unicode.IsTitle(rr) {
			bits |= 1 << 11
		}
		if unicode.IsUpper(rr) {
			bits |= 1 << 12
		}
		fmt.Fprintf(&b, "    %d,\n", bits)
	}
	b.WriteString("];\n")

	out := filepath.Join(dir, "src", "generated.rs")
	if err := os.WriteFile(out, []byte(b.String()), 0o644); err != nil {
		panic(err)
	}
}

func writeNamesDts(dir string, named []namedTable) {
	var lines []string
	for _, n := range named {
		lines = append(lines, fmt.Sprintf("  | %q", n.Name))
	}
	content := "/** Code generated by tools/gentables. DO NOT EDIT. */\nexport type RangeTableName =\n" + strings.Join(lines, "\n") + ";\n"
	if err := os.WriteFile(filepath.Join(dir, "generated-names.d.ts"), []byte(content), 0o644); err != nil {
		panic(err)
	}
}

func runs(pred func(rune) bool) [][2]uint32 {
	var out [][2]uint32
	var start uint32
	in := false
	flush := func(end uint32) {
		if in {
			out = append(out, [2]uint32{start, end})
			in = false
		}
	}
	for r := rune(0); r <= unicode.MaxRune; r++ {
		if pred(r) {
			if !in {
				start = uint32(r)
				in = true
			}
		} else {
			flush(uint32(r - 1))
		}
	}
	flush(uint32(unicode.MaxRune))
	return out
}

type fixtureFile struct {
	Version    string                `json:"version"`
	GoVersion  string                `json:"goVersion"`
	TableNames []string              `json:"tableNames"`
	TableCount int                   `json:"tableCount"`
	Predicates map[string][][2]uint32 `json:"predicates"`
	CaseNonID  [][5]int32            `json:"caseNonIdentity"`
	Special    map[string][][4]int32 `json:"specialCase"`
	Utf8       utf8Fix               `json:"utf8"`
	Utf16      utf16Fix              `json:"utf16"`
	JsDiffs    jsDiffs               `json:"jsDiffs"`
	RandomUtf8 randomUtf8            `json:"randomUtf8"`
}

type randomUtf8 struct {
	Len       int  `json:"len"`
	Valid     bool `json:"valid"`
	RuneCount int  `json:"runeCount"`
}

type utf8Fix struct {
	SingleByte [][3]int     `json:"singleByte"`
	Samples    []utf8Sample `json:"samples"`
	RuneLen    [][2]int32   `json:"runeLen"`
}

type utf8Sample struct {
	Hex  string `json:"hex"`
	R    int32  `json:"r"`
	Size int    `json:"size"`
	Valid bool  `json:"valid"`
}

type utf16Fix struct {
	Encode      []utf16Enc `json:"encode"`
	DecodeLone  [][2]int32 `json:"decodeLone"`
	Surrogate   [][2]any   `json:"surrogate"`
	RuneLen     [][2]int32 `json:"runeLen"`
	EncodeRune  [][3]int32 `json:"encodeRune"`
}

type utf16Enc struct {
	R     int32   `json:"r"`
	Units []uint16 `json:"units"`
}

type jsDiffs struct {
	ToUpper [][2]string `json:"toUpper"`
	ToLower [][2]string `json:"toLower"`
}

func lcgBytes(n int) []byte {
	var x uint32 = 1
	b := make([]byte, n)
	for i := range b {
		x = x*1664525 + 1013904223
		b[i] = byte(x >> 24)
	}
	return b
}

func hexBytes(p []byte) string {
	var b strings.Builder
	for i, x := range p {
		if i > 0 {
			b.WriteByte(' ')
		}
		fmt.Fprintf(&b, "%02x", x)
	}
	return b.String()
}

func decodeSample(p []byte) utf8Sample {
	r, size := utf8.DecodeRune(p)
	return utf8Sample{Hex: hexBytes(p), R: r, Size: size, Valid: utf8.Valid(p)}
}

func writeFixtures(dir string, named []namedTable) {
	names := make([]string, len(named))
	for i, n := range named {
		names[i] = n.Name
	}
	fx := fixtureFile{
		Version:    unicode.Version,
		GoVersion:  runtime.Version(),
		TableNames: names,
		TableCount: len(named),
		Predicates: map[string][][2]uint32{
			"isControl": runs(unicode.IsControl),
			"isDigit":   runs(unicode.IsDigit),
			"isGraphic": runs(unicode.IsGraphic),
			"isLetter":  runs(unicode.IsLetter),
			"isLower":   runs(unicode.IsLower),
			"isMark":    runs(unicode.IsMark),
			"isNumber":  runs(unicode.IsNumber),
			"isPrint":   runs(unicode.IsPrint),
			"isPunct":   runs(unicode.IsPunct),
			"isSpace":   runs(unicode.IsSpace),
			"isSymbol":  runs(unicode.IsSymbol),
			"isTitle":   runs(unicode.IsTitle),
			"isUpper":   runs(unicode.IsUpper),
		},
		Special: map[string][][4]int32{},
	}
	for r := rune(0); r <= unicode.MaxRune; r++ {
		u, l, t := unicode.ToUpper(r), unicode.ToLower(r), unicode.ToTitle(r)
		f := unicode.SimpleFold(r)
		if u != r || l != r || t != r || f != r {
			fx.CaseNonID = append(fx.CaseNonID, [5]int32{r, u, l, t, f})
		}
	}
	samples := []rune{'I', 'i', 0x0130, 0x0131, 'A', 'a', 0x00DF, 0xFB01, ' '}
	for _, r := range samples {
		fx.Special["turkish"] = append(fx.Special["turkish"], [4]int32{
			r, unicode.TurkishCase.ToUpper(r), unicode.TurkishCase.ToLower(r), unicode.TurkishCase.ToTitle(r),
		})
		fx.Special["azeri"] = append(fx.Special["azeri"], [4]int32{
			r, unicode.AzeriCase.ToUpper(r), unicode.AzeriCase.ToLower(r), unicode.AzeriCase.ToTitle(r),
		})
	}

	for b := 0; b < 256; b++ {
		p := []byte{byte(b)}
		r, size := utf8.DecodeRune(p)
		fx.Utf8.SingleByte = append(fx.Utf8.SingleByte, [3]int{b, int(r), size})
	}
	samples8 := [][]byte{
		{},
		{0x00},
		{0x7f},
		{0x80},
		{0xc0, 0x80},
		{0xc2, 0x80},
		{0xdf, 0xbf},
		{0xe0, 0x80, 0x80},
		{0xe0, 0xa0, 0x80},
		{0xed, 0x9f, 0xbf},
		{0xed, 0xa0, 0x80},
		{0xee, 0x80, 0x80},
		{0xef, 0xbf, 0xbd},
		{0xf0, 0x80, 0x80, 0x80},
		{0xf0, 0x90, 0x80, 0x80},
		{0xf4, 0x8f, 0xbf, 0xbf},
		{0xf4, 0x90, 0x80, 0x80},
		{0xf5, 0x80, 0x80, 0x80},
		{0xff},
		{0xc2},
		{0xe0, 0xa0},
		{0xf0, 0x90, 0x80},
		[]byte("😀"),
		{0xef, 0xbf, 0xbd},
	}
	for _, p := range samples8 {
		fx.Utf8.Samples = append(fx.Utf8.Samples, decodeSample(p))
	}
	for _, r := range []int32{-1, 0, 0x7f, 0x80, 0x7ff, 0x800, 0xd800, 0xdfff, 0xffff, 0x10000, 0x10ffff, 0x110000, utf8.RuneError} {
		fx.Utf8.RuneLen = append(fx.Utf8.RuneLen, [2]int32{r, int32(utf8.RuneLen(r))})
	}

	for _, r := range []rune{0, 'A', 0xD800, 0xDFFF, 0xFFFF, 0x10000, 0x1F600, 0x10FFFF, 0x110000, -1} {
		units := utf16.Encode([]rune{r})
		fx.Utf16.Encode = append(fx.Utf16.Encode, utf16Enc{R: r, Units: units})
		fx.Utf16.RuneLen = append(fx.Utf16.RuneLen, [2]int32{r, int32(utf16.RuneLen(r))})
		r1, r2 := utf16.EncodeRune(r)
		fx.Utf16.EncodeRune = append(fx.Utf16.EncodeRune, [3]int32{r, r1, r2})
		fx.Utf16.Surrogate = append(fx.Utf16.Surrogate, [2]any{r, utf16.IsSurrogate(r)})
	}
	fx.Utf16.DecodeLone = [][2]int32{{0xD83D, 0xFFFD}, {0xDE00, 0xFFFD}}
	decoded := utf16.Decode([]uint16{0xD83D, 0xDE00})
	_ = decoded

	randBuf := lcgBytes(1 << 20)
	fx.RandomUtf8 = randomUtf8{Len: len(randBuf), Valid: utf8.Valid(randBuf), RuneCount: utf8.RuneCount(randBuf)}

	fx.JsDiffs = jsDiffs{
		ToUpper: [][2]string{{"ß", string(unicode.ToUpper('ß'))}, {"ﬁ", string(unicode.ToUpper('ﬁ'))}, {"ı", string(unicode.ToUpper('ı'))}},
		ToLower: [][2]string{{"İ", string(unicode.ToLower('İ'))}},
	}

	raw, err := json.MarshalIndent(fx, "", "  ")
	if err != nil {
		panic(err)
	}
	out := filepath.Join(dir, "test", "fixtures", "go.json")
	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		panic(err)
	}
	if err := os.WriteFile(out, raw, 0o644); err != nil {
		panic(err)
	}
}

func writeTableRuns(dir string, named []namedTable) {
	// Compact per-table true-runs for isTable replay. Change-points only.
	type file struct {
		Names map[string][][2]uint32 `json:"tables"`
	}
	f := file{Names: map[string][][2]uint32{}}
	for _, n := range named {
		tab := n.Table
		f.Names[n.Name] = runs(func(r rune) bool { return unicode.Is(tab, r) })
	}
	raw, err := json.Marshal(f)
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "test", "fixtures", "tables.json"), raw, 0o644); err != nil {
		panic(err)
	}
}

func main() {
	dir := "."
	if _, err := os.Stat("Cargo.toml"); err != nil {
		dir = "../.."
	}
	named := allNamedTables()
	writeGeneratedRust(dir, named)
	writeNamesDts(dir, named)
	writeFixtures(dir, named)
	writeTableRuns(dir, named)
	fmt.Printf("generated %d range table names, unicode %s, go %s\n", len(named), unicode.Version, runtime.Version())
}
